server:
  port: ${SPRING_PORT}

spring:
  application:
    name: money-plan

  profiles:
    active: local

  # MySQL 데이터베이스 설정
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        highlight_sql: true

  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  web:
    resources:
      add-mappings: false # 정적 리소스 매핑 비활성화

# JWT 설정
jwt:
  secret: ${JWT_SECRET}

logging:
  config: classpath:logback-${spring.profiles.active}.xml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: prod
